<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/pandas/DF_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

**tartiblash(sort) va reytinglash(ranking)**
1. Seriesni indeks bo'yicha tartiblash
2. Seriesni qiymatlari bo'yicha tartiblash
3. DF uchun indeks bo'yicha tartiblash
4. DF da ustunlar nomi bo'yicha tartiblash (alfabet bo'yicha tahlanadi) `df.sort_index(axis=1)` bunda inplace ni parametr qilib berishimiz mumkin
5. ascending - o'sishga teskari , parametri yordamida DF ning indekslarini va ustunlarini teskari tartiblashimiz mumkin `df.sort_index(ascending=False)` yoki `df.sort_index(axis=1, ascending=False)`
6. DF ning biror ustuni bo'yicha qiymatlarini (o'sish) tartiblash | by parametri `df.sort_values(by='ustun_nomi')` buni ham ascending bilan kamayish tartibida joylashtirishimiz mumkin
7. bir vaqtni o'zida DF ning bir necha ustunlarini qiymatlari bo'yicha tartiblash `by=[ustunlar]` ascending ishlatsek bo'ladi

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
# indeks bo'yicha tartiblash
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
# qiymat bo'yicha tartiblash
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
# KEling keyingi mashqlar uchun Githubdan kattaroq DF yuklab olamiz
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
# indeks bo'yicha tartiblash
df.sort_index()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [ ]:
# ustunlar nomini tartiblash
df.sort_index(axis=1)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
df.sort_index(axis=1, inplace=True)

In [ ]:
df.head()

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018

In [ ]:
# jadvalning indekslarini va ustunlarini teskari tartiblash
df.sort_index(ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008

In [ ]:
# jadval ustunlarini teskari tartiblash
df.sort_index(axis=1, ascending=False)

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan

In [ ]:
# jadvalning biror ustunining qiymatlarini tartiblash
df.sort_values(by='year')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
32,chevrolet,red,22 hours left,usa,167763370,46226,camaro,29800,pennsylvania,clean vehicle,1q87t3n166389,1973
405,ford,white,17 hours left,usa,167611661,41577,door,25,arkansas,salvage insurance,2ftcf15y9eca14589,1984
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
362,ford,white,2 days left,usa,167361489,206162,pickup,25,georgia,salvage insurance,1ftdf15y2rnb12612,1994
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
...,...,...,...,...,...,...,...,...,...,...,...,...
426,lexus,silver,2 days left,usa,167605747,8186,gx,55600,florida,clean vehicle,jtjam7bx4l5251250,2020
806,chevrolet,silver,2 days left,usa,167805497,13886,colorado,28300,indiana,clean vehicle,1gcgtcen7l1101496,2020
2322,nissan,blue,2 days left,usa,167656212,14320,altima,15000,ohio,clean vehicle,1n4bl4cv4lc134145,2020
2344,nissan,blue,14 hours left,usa,167614842,10875,rogue,20100,minnesota,clean vehicle,jn8at2mvxlw103235,2020
1388,ford,gray,2 days left,usa,167742945,1117,fusion,17000,pennsylvania,clean vehicle,3fa6p0d98lr194138,2020

In [ ]:
df.sort_values(by='price')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
410,chevrolet,green,2 days left,usa,167425634,274706,door,0,arizona,salvage insurance,2gcec19h8s1195266,1995
330,ford,green,19 hours left,usa,167359712,296860,door,0,california,salvage insurance,1falp62w5th144314,1996
331,ford,red,17 hours left,usa,167610991,203158,door,0,illinois,salvage insurance,1fmzk04136ga07119,2006
339,ford,black,2 days left,usa,167360232,214800,door,0,south carolina,salvage insurance,3fafp37372r151014,2002
496,ford,red,17 hours left,usa,167357804,252588,pickup,0,oklahoma,salvage insurance,1ftef15n0tlc14455,1996
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017

In [ ]:
# ascending bilan yuqoridagini teskari tartiblash
df.sort_values(by='year', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2339,nissan,silver,14 hours left,usa,167614830,14850,rogue,19800,minnesota,clean vehicle,knmat2mv2lp511637,2020
399,bmw,black,7 days left,usa,167417053,7509,series,61200,california,clean vehicle,wba7t2c04lgl17687,2020
2305,nissan,gray,2 days left,usa,167743353,15387,rogue,14700,pennsylvania,clean vehicle,knmat2mv5lp500471,2020
2302,nissan,silver,21 hours left,usa,167725016,19597,rogue,21100,south carolina,clean vehicle,5n1at2mt6lc714032,2020
1704,ford,black,21 hours left,usa,167751305,7,escape,25200,virginia,clean vehicle,1fmcu9f61lua48374,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
362,ford,white,2 days left,usa,167361489,206162,pickup,25,georgia,salvage insurance,1ftdf15y2rnb12612,1994
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
405,ford,white,17 hours left,usa,167611661,41577,door,25,arkansas,salvage insurance,2ftcf15y9eca14589,1984
32,chevrolet,red,22 hours left,usa,167763370,46226,camaro,29800,pennsylvania,clean vehicle,1q87t3n166389,1973

In [ ]:
df.sort_values(by='price', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
141,dodge,orange,2 days left,usa,167756157,177948,van,0,utah,salvage insurance,2d8hn44h88r669549,2008
391,cadillac,white,9 days left,usa,167651218,105169,coupe,0,virginia,salvage insurance,1g6el12y9yu148063,2000
285,ford,black,17 hours left,usa,167251902,124969,door,0,oklahoma,salvage insurance,1fafp34p7yw270338,2000
290,mazda,gray,16 hours left,usa,167543177,117541,door,0,indiana,salvage insurance,jm3er293590215768,2009
354,ford,blue,2 days left,usa,167360535,180364,pickup,0,tennessee,salvage insurance,1ftyr10d19pa60391,2009

In [ ]:
# bir vaqtning o'zida bir necha ustunni qiymatlarini tartiblash
df.sort_values(by=['price', 'year'], ascending=True)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
410,chevrolet,green,2 days left,usa,167425634,274706,door,0,arizona,salvage insurance,2gcec19h8s1195266,1995
330,ford,green,19 hours left,usa,167359712,296860,door,0,california,salvage insurance,1falp62w5th144314,1996
496,ford,red,17 hours left,usa,167357804,252588,pickup,0,oklahoma,salvage insurance,1ftef15n0tlc14455,1996
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017